### ISSUE TITLE
allow custom OSRM servers

### ISSUE THREAD

**Issue by emiltin** [mapbox/MapboxNavigation.swift#46]
many users of OSRM run their own OSRM servers. it would make MapboxNavigation.swift more useful if it's easy to connect to your own OSRM server.

a problem is that the mapbox directions API does not return raw OSRM responses, but use a node app to modify/amend it before returning it. either the expected format should be documented or the code used to modify the OSRM response should be open sourced.

**Comment by willylambert** [comment]
Exactly the feature i'm looking for.

**Comment by 1ec5** [comment]
MapboxNavigation.swift doesn't deal with API responses directly; it uses Route objects that MapboxDirections.swift creates from the API response. MapboxDirections.swift has [methods](https://github.com/mapbox/MapboxDirections.swift/blob/12f1e9648a74bae34f92c6da8f6e5eb152c7c8d8/MapboxDirections/MBRoute.swift#L29) to produce Route objects from JSON (deserialized as Foundation objects).

My understanding is that the OSRM v5 and Directions API v5 responses are already very similar, so an OSRM response wouldn't need to be modified heavily before being passed into those JSON-based initializers. Still, I agree that it would be nice for MapboxDirections.swift to have built-in support for OSRM v5 alongside the existing support for Directions API v4 and v5: mapbox/MapboxDirections.swift#121.

Closing, because there won't be anything to modify in this project once MapboxDirections.swift gains OSRM support.

**Comment by blinters** [comment]
so whats the conclusion?

**Comment by 1ec5** [comment]
It’s already possible to use this library with a custom OSRM server, as long as you go through some trouble to pass the right JSON structure into [`Route(json:waypoints:routeOptions:)`](https://github.com/mapbox/MapboxDirections.swift/blob/76f79a8d6f5300199da31706cdb780700f9dcb4c/MapboxDirections/MBRoute.swift#L29). Please see mapbox/MapboxDirections.swift#121, which would simplify this step so that you’d be able to pass in an unmodified OSRM response.

This ticket is closed because MapboxNavigation and MapboxCoreNavigation use the Route object created by MapboxDirections.swift, regardless of the server endpoint that provided the underlying data.

**Comment by blinters** [comment]
will try it out! thanks pal!

**Comment by blinters** [comment]
Has anyone managed to connect to your own OSRM server and modify your own JSON response structure? 1ec5 mentioned  mapbox/MapboxDirections.swift#121 "which would simplify this step so that you’d be able to pass in an unmodified OSRM response". Apparently that post doesn't have much information to go about doing it

**Comment by 1ec5** [comment]
Since MapboxDirections.swift currently only knows how to issue requests to the Mapbox Directions API, you’ll need to write your own code to construct the request URL to your OSRM server and send a request using URLRequest (in Swift) or NSURLRequest (in Objective-C). Then, use JSONSerialization/NSJSONSerialization to turn the response data into a Dictionary/NSDictionary before passing it to the Route initializer.

You’ll want to compare the [OSRM response format](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#route-object) with the [Mapbox Directions API response format](https://www.mapbox.com/api-documentation/#directions-response-object). Modify the dictionary representation of the response data to match the Directions API format. They already look very similar; I couldn’t spot any differences at a glance.

**Comment by bobberkarl** [comment]
Any news on this particular issue?

**Comment by sajeel** [comment]
Any update?
